### ISSUE TITLE
[샐리] split() 함수의 default 인자

### ISSUE THREAD

**Issue by bsm8734** [boostcamp-ai-tech-4/peer-session#14]
### **🙌 질문자**

-  `샐리` @bsm8734 

----

### **❓ 질문 내용**

```
s = "Hello    World"
s.split()     # ['Hello', 'World']
s.split(' ')  # ['hello', '', '', '', 'World']
```
- 둘의 차이가 나는 이유가 무엇일까요?

----

### **📄 참고 자료**

- [파이썬 표준 라이브러리](https://docs.python.org/ko/3/library/stdtypes.html?highlight=split )

----

**Comment by bsm8734** [comment]
[파이썬 표준 라이브러리](https://docs.python.org/ko/3/library/stdtypes.html?highlight=split)에 따르면, split 함수의 첫번째 파라미터 값(sep)에 따라 서로 다른 분할 알고리즘이 적용된다고 합니다.

---

### string.split()
- sep is None  (default)
- `string.split(sep = None)` 인 경우,  연속된 공백 문자는 단일한 구분자로 간주하고,   
  문자열이 선행이나 후행 공백을 포함해도 결과는 시작과 끝에 빈 문자열을 포함하지 않습니다.

### string.split(' ')
- sep is not None
- `sep`이 주어지는 경우, 연속된 구분자는 묶이지 않고, 빈 문자열을 구분하는 것으로 간주합니다.  

  ```python
  "abc  def".split(' ') # ['abc']
  ```

---

```python
# 개인적인 생각이지만 아래와 같은 순서로 잘리지 않을까.. 추측해봅니다!
# 1 # "abc  def"
# 2 # "abc", "  def"
# 3 # "abc", "", "def"
```

**Comment by Heeseok-Jeong** [comment]
유익합니다!
