### ISSUE TITLE
[엠제이] iterator와 iterable 어떻게 다른가/리스트는 interator가 아닌가

### ISSUE THREAD

**Issue by mj950425** [boostcamp-ai-tech-4/peer-session#16]
### **🙌 질문자**

-  #### "엠제이' @mj950425

----

### **❓ 질문 내용**
- list는 iterator가 아닌가?
- iterator와 iterable의 차이점은?
![image](https://user-images.githubusercontent.com/52944973/105466406-8724ec00-5cd7-11eb-9439-36552404395f.png)

![image](https://user-images.githubusercontent.com/52944973/105466481-9f950680-5cd7-11eb-9b11-1d176fa22cd6.png)
----

**Comment by mj950425** [comment]
iterable 의 의미는 member를 하나씩 차례로 반환 가능한 object를 말한다. 
 iterable 의 예로는 sequence type인 list, str, tuple 이 대표적이다. 
우리가 사용하는 list는 iteratable 하기 때문에 for문으로 인덱스 하나 하나에 접근이 가능하다고 한다.
__iter__() 로 정의된 클래스는 전부 interable 하다고 말할 수 있다고 한다.

 Iterator 는 next() 메소드로 데이터를 순차적으로 호출 가능한 object 이다.
하지만 iterable한 객체는 전부 iterator라고 할 수는 없다고 한다.

위의 그림처럼 list는 iterator가 아니다. iterator를 iterable하게 바꿔주고 싶다면 iter() 메소드를 사용하면 된다. 우리가 사용하는 list가 next와 같이 for문으로 차례대로 호출이 가능한 이유는 for문이 자동적으로 list를 iterator로 변환해주어서 가능하다고 한다.


### **📄 참고 자료**  https://bluese05.tistory.com/55

**Comment by Heeseok-Jeong** [comment]
앗 혹시 MJ 님, iter() 함수에 iterable 한 객체를 넣으면 iterator 객체로 나오니까 `iterator를 iterable하게 바꿔주고 싶다면 iter() 메소드를 사용하면 된다` 이 부분 반대 아닐까요?!

**Comment by mj950425** [comment]
헉 맞네요 감사합니다!

**Comment by mj950425** [comment]
> 앗 혹시 MJ 님, iter() 함수에 iterable 한 객체를 넣으면 iterator 객체로 나오니까 `iterator를 iterable하게 바꿔주고 싶다면 iter() 메소드를 사용하면 된다` 이 부분 반대 아닐까요?!

헉 맞네요!! 감사합니다
