### ISSUE TITLE
[DAY 05] 파이썬으로 데이터 다루기

### ISSUE THREAD

**Issue by CoodingPenguin** [boostcamp-ai-tech-4/peer-session#17]
벌써 한 주차가 마무리 됐네요. 오늘은 한 주가 마무리가 된 기념으로 `회고`를 해보았습니다!

---

#### `후미` @opijae 
쉬엄쉬엄해야지 했는데 할게 꽤 많았다. 기존에는 파이썬을 정식 학교 수업에서 배운 게 아니라 직접 찾아가며 배워 미숙한 부분이 많았는데 리스트 복사, 포맷팅 등 조금 더 파이썬을 깊게 배울 수 있어서 좋았다.

#### `펭귄` @CoodingPenguin 
파이썬을 정말 좋아해서 파이썬을 깊이 팠는데도 어려워서 넘어간 개념들을 다시 짚을 수 있어서 좋았다. 그리고 부스트캠프 시작 전에 팀 활동을 한다고 해서 많이 걱정을 했는데 정말 좋은 팀을 만나서 정말 좋았다.

#### `원딜` @changwoomon 
모르는 부분을 더 자세히 배울 수 있어서 좋았다. 부스트코스에서 최성철 마스터님의 강의를 미리 들었었는데 지금 마스터님의 강의를 들으면서 다시 열심히 공부하는 마음으로 공부를 했다. 

#### `샐리` @bsm8734 
팀 Github를 잘 꾸며주셔서 좋았다. (감사합니다!!🙇‍♀️) 그리고 좋은 사람들을 만나서 피어세션이 정말 재미있었고 파이썬을 다 안다고 생각했는데 데코레이터 등의 내용을 들을 때 새로웠고 뒷부분을 조금 더 꼼꼼히 공부해야겠다.

#### `히스` @Heeseok-Jeong 
모르는 건 대충 짚고 넘어가는 경우가 많았는데 모르는 것을 계속 찾아보며 공부하게 되었다. 앞으로도 잘 헤쳐나가겠다!

#### `엠제이` @mj950425 
부스트캠프를 하기 전에 많이 바빠서 지쳤는데 지금은 피어세션이 기다려질만큼 재미있다. 특히 코드 리뷰를 하면서 짧고 간결하게 적는 습관을 들여야겠다고 생각했고 팀원들이 정말 좋아서 매 피어세션이 기다려진다.

#### `서폿` @keepRainy 
부스트캠프 오기 전에 다른 활동이랑 부캠이랑 고민을 했었는데 좋은 팀원을 만난 것을 보고 잘한 선택이라고 생각한다. 또한 이번 주에 강의를 들으면서 파이썬을 많이 배울 수 있어서 좋았다.

---

#### ✅ 그날 강의 피어세션 때 질문하기 by @Heeseok-Jeong  
- 오전에 강의를 다 듣고 피어세션 때 질문을 한다.
- 답변을 아는 팀원은 답을 하고 답변을 얻지 못하면 Issue에 남겨서 다같이 생각해보자.

#### ⏸ 책/강의를 정해서 같이 공부하기 by @keepRainy 
- 하루에  알고리즘 문제 1문제 공유해서 같이 풀기 or 책/강의 같이 공부하기
- 스터디 느낌이 좀 있고 아직 1주차라 조금 더 경과를 지켜보고 결정하기로 함.

#### ✅ 매주 수요일 짧은 세미나 갖기 by @CoodingPenguin 
- 짧은 시간동안 자신이 아는 것을 발표하는 시간을 갖는다. (부담없이 진행)
- 다음 주부터 진행하며 첫 주자로 `원딜`님과 `후미`님이 시작합니다!
```python
seminar = {
    "요일": "수요일",
    "시간": "발표, QnA 각각 최대 10분"
    "형식": "자유"
    "인원": 2
    "우선순위": 0
}
```

---

### ❓ 질문

- `엠제이`님의 Iterator와 Iterable 관련 질문: #16 

---

#### is_validated_english_sentence
- `엠제이`: set을 이용해 ",.!?"을 제거한다.
- `원딜`: 각 조건에 대한 True, False로 이루어진 리스트를 만들어 any를 사용해서 cond을 계산하고 최종 결과도 any를 사용해서 계산한다.
- `서폿`: 정규식을 사용 findall과 sub 사용해서 3가지 조건 합해서 계산한다.
  - `re.sub`보다는 `replace`가 조금 더 빠르다고 합니다! 자세한 내용은 [여기](https://stackoverflow.com/questions/3411771/best-way-to-replace-multiple-characters-in-a-string)를 참고해주세요. 

#### encoding_sentence, decoding sentence
- letter 따로 word 따로 변환해야 해서 `encoding_word`, `decoding_word`을 따로 만드는 게 더 깔끔해보인다!
- `모스부호 -> 알파벳`으로 가는 reversed_dict를 미리 만들어 놓는다.
 ```python
# 방법 1. 서폿님
dict(zip(d.values(), d.keys()))
# 방법 2. 히스님
dict(map(reversed, d.items()))
```
---

**Comment by Heeseok-Jeong** [comment]
감사합니다!!

**Comment by mj950425** [comment]
일주일 동안 고생 많으셨어요

**Comment by bsm8734** [comment]
회의, 깃헙그룹(?), 다양한 양식 들에 대해서... 첫 틀을 너무 잘 잡아주셔서 좋았어용 감사합니다 ! ><

**Comment by changwoomon** [comment]
진짜 고생 많으셨습니다.. ㅎㅎ
