### ISSUE TITLE
[DAY 06] Numpy / 벡터 / 행렬

### ISSUE THREAD

**Issue by keepRainy** [boostcamp-ai-tech-4/peer-session#18]
2주차가 시작되었습니다 / 이번주도 모두 ```화이팅```입니다!

---

#### `히스` (희석님) @Heeseok-Jeong 

* 윤스테이 시청
* 알고리즘 공부 조금
* 친구랑 걸어서 광안리 구경

하셨습니다

#### `후미` (재혁님) @opijae 

* 개인 프로젝트
* 롤챔스 시청

하셨습니다

#### `펭귄` (소현님) @CoodingPenguin 

* 잠
* 유튜브 시청 (주제: 슬라임)

하셨습니다

#### `샐리`(수민님) @bsm8734 

* 블로그 만드는데 자꾸 에러, 잠을 못잠
* 그것이 알고 싶다 / 오! 삼광빌라 시청

하셨습니다

#### `엠제이` (민준님) @mj950425 

* 잠을 못잠
* 친구랑 술
* 논문 스터디
* 넥슨 데이터 분석 인턴 대비
* 블로그 꾸미기

하셨습니다

#### `원딜` (창우님) @changwoomon 

* 올빼미형 -> 아침형 인간 부작용
* 유튜브 시청 (주제: 더 지니어스 feat. 장동민)

하셨습니다

#### `서폿` (홍균님) @keepRainy 

* 유뷰티 시청 (주제: 실화탐사대)
* 봉사활동

하셨습니다

---

### ❓질문

* ```샐리```님의 np.array Slice Indexing 관련 질문
* ```서폿```님의 NBSP 관련 질문

---

### 📝학습정리 리뷰

* ```엠제이``` : <https://minjoon950425.tistory.com/>
* ```후미``` : <https://www.notion.so/68b7e21a669c439d9e985655a5c0b606?v=6cda9d3b5e824db8b57ffb700874b190>
* ```펭귄``` : <https://cooding-penguin.netlify.app/boostcamp/day4-20210121/>
* ```원딜``` : <https://github.com/changwoomon/Boostcamp-AI-Tech/blob/main/Week%201/%5BDay%205%5D%20%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9C%BC%EB%A1%9C%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb>
* ```히스``` : <https://heeseok-jeong.github.io/>
* ```샐리``` : <https://bsm8734.github.io>
* ```서폿``` : <https://gglifer-cs.tistory.com/163?category=836569>
---

### 🙌 제안

✅ TMI 세미나 by @changwoomon 

* 피어세션 마지막 10분 (3:20 PM 부터)
* 자기소개 + QnA (익명카톡방, 오픈카톡방 링크로)
  * 자기소개 = 공통질문 2개 + 본인 TMI (노코멘트 가능)
    * 질문 1. 가장 본인에게 영향을 끼친 사건과 인물을 서술하시오(150자 이내)
    * 질문 2. MBTI
* 일정
  * 화(1/26) / `원딜`
  * 수(1/27) / `서폿`
  * 목(1/28) / `후미`
  * 금(1/29) / `엠제이`
  * 월(2/1) / `펭귄`
  * 화(2/2) / `샐리`
  * 수(2/3) / `히스`

**Comment by bsm8734** [comment]
정리감사합니다 !! ^^ 일주일동안 화잇팅!
