### ISSUE TITLE
[펭귄] 특정 axis 방향에서의 행렬 연산

### ISSUE THREAD

**Issue by CoodingPenguin** [boostcamp-ai-tech-4/peer-session#20]
가장 간단한 `sum` 연산을 가지고 생각해보겠습니다!

---

### 2차원 배열

다음과 같이 (2, 3) 크기의 2차원 배열이 있다고 생각합시다.

![image](https://user-images.githubusercontent.com/37505775/105709238-c746d180-5f58-11eb-90b4-9275f01306fc.png)

#### axis=0방향으로 sum을 한다면
해당 방향으로 요소가 다 더해지겠죠?
- 결과: [5, 7, 9] = [1+4, 2+5, 3+6]
- 크기: (3, )

이 됩니다. 원 행렬의 크기 (2, 3)과 비교해보면, axis=0 방향으로 더해지면서 axis=0이 없어지는 것을 볼 수 있습니다. 

#### axis=1방향으로 sum을 한다면
앞에 처럼 똑같이 더해주면 다음과 같습니다.
- 결과: [6, 15] = [1+2+3, 4+5+6]
- 크기: (2, )

똑같이 axis=1 방향으로 더해지면서 원 행렬의 크기 (2, 3)과 비교할 때, axis=1이 없어지는 것을 볼 수 있습니다.

**즉, axis=n을 설정하면 해당 방향으로 연산을 하면서 그 결과가 하나가 되기 때문에 해당 axis가 사라지는 것을 볼 수 있습니다.**

----

### 3차원 배열

자 이번에는 (4, 2, 3) 크기의 3차원 배열입니다.

![image](https://user-images.githubusercontent.com/37505775/105713605-b305d300-5f5e-11eb-8dba-6c99c6b15545.png)

여기서 퀴즈! axis=0, 1, 2로 각각 sum을 했을 때를 생각해봅시다. 답은 내일 작성하겠습니다.

---

### 참고자료

[파이토치로 시작하는 딥러닝 - Lab 01-1. Tensor Manipulation 1](https://www.boostcourse.org/ai214/lecture/42282) 26:00 부터

**Comment by Heeseok-Jeong** [comment]
흠.. 3차원일때도 2차원일때처럼 그 축이 사라져서 2차원이 행렬이 되지않을까요?!
x.shape => (4, 2, 3)
axis=0 : (2, 3)
axis=1 : (4, 3)
axis=2 : (4, 2)

**Comment by bsm8734** [comment]
와 근데 펭귄님이 말씀하신대로 해당 축이 사라진다고 생각하니까 정말 편리하네요! ..🔥
답은 다른 종이에 살짝 적어놓고 내일 맞춰보겠습니다 : - )

**Comment by CoodingPenguin** [comment]
@Heeseok-Jeong @bsm8734 늦어서 죄송합니다..ㅠㅠ

---

히스님이 말씀하신대로 설정된 축이 없어지니 **결과의 크기**는

- `axis=0` : (2, 3)
- `axis=1` : (4, 3)
- `axis=2` : (4, 2)

되는 게 맞습니다!

자세한 결과는 다음과 같습니다.

- `axis=0` : [[4, 8, 12], [16, 20, 24]]
- `axis=1` : [[5, 7, 9], [5, 7, 9], [5, 7, 9], [5, 7, 9]]
- `axis=2` : [[6, 15], [6, 15], [6, 15], [6, 15]]

가 됩니다!

---

도움이 되서 다행이네요😊
