### ISSUE TITLE
[히스] 벡터간 유사도와 내적

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#21]
### **🙌 질문자**

-  히스@Heaseok-Jeong

----

### **❓ 질문 내용**

- 내적을 이용하면 벡터간 유사도를 측정할 수 있다고 수업에서 들었는데요.
- 1. 벡터간 유사도가 뭘까요?
- 2. 내적으로 어떻게 알 수 있을까요?

----

**Comment by bsm8734** [comment]
cosine similarity를 찾아보시면 좋을거같아요!

**Comment by bsm8734** [comment]
cosine similarity를 찾아보시면 좋을거같아요!

---

유사도는 다차원 공간의 두 점의 거리를 나타내는데, 이 거리가 짧을수록 유사도가 높다고 할 수 있습니다.
떨어져 있는 두 벡터보다는, 비슷한 위치에 있는 두 벡터가 확실히 더 비슷하겠죠!
따라서, 벡터간 유사도는 벡터간 거리로 나타낼 수 있습니다. (방향과 길이)
벡터 간의 거리를 재는 방식이 여러 개인 만큼, 유사도를 여러 방법으로 구할 수 있습니다!

사실 우리가 배웠던 L1-norm과 L2-norm은 하나의 식에 인자를 대입한 값으로 나타낼 수 있습니다.

r = 1: City Block Distance(= Manhattan, L1-norm)
r = 2: Euclidean Distance(=L2-norm)
등등

**Comment by bsm8734** [comment]
cosine similarity를 찾아보시면 좋을거같아요!

---

**유사도는 다차원 공간의 두 점의 거리**를 나타내는데, 이 **거리가 짧을수록 유사도가 높다**고 할 수 있습니다.
떨어져 있는 두 벡터보다는, 비슷한 위치에 있는 두 벡터가 확실히 더 비슷하겠죠!
따라서, 벡터간 유사도는 벡터간 거리로 나타낼 수 있습니다.
벡터 간의 거리를 재는 방식이 여러 개인 만큼, 유사도를 여러 방법으로 구할 수 있습니다!

사실 우리가 배웠던 L1-norm과 L2-norm은 하나의 식에 인자를 대입한 값으로 나타낼 수 있습니다.

![image](https://user-images.githubusercontent.com/35002768/105737733-a3e04e80-5f79-11eb-9c1e-d73eb9b38b7f.png)
(➡ Minkowski Distance)

**r = 1: City Block Distance(= Manhattan, L1-norm)** - (r = 1)차원 데이터간의 거리를 측정하기에 적당
**r = 2: Euclidean Distance(=L2-norm)** - (r = 2)차원 거리를 측정하기에 적당
등등

이러럼 L1, L2 norm이 단순히 거리를 고려하는 거리(유사도)라면,
내적의 식은 cosine similarity의 식과 동일하며

![image](https://user-images.githubusercontent.com/35002768/105738773-beff8e00-5f7a-11eb-8d44-4ef3767ea44d.png)


내적(코사인유사도)는 **방향과 길이**를 모두 고려할 수 있기에 사용됩니다!

라고 알고있습니당...! 혹시 잘못알고있는부분이 있다면 알려주세요 !😀

**Comment by mj950425** [comment]
---

저도 궁금해서 찾아봤는데 코사인 유사도 뿐 아니라 이러한 방식도 있다고 합니당
가장 비슷한 문서는 아마 B,C인거 같은데 오타같습니다!

---

> ![image](https://user-images.githubusercontent.com/52944973/105781817-91d0d100-5fb6-11eb-97e5-33535fcf1ca3.png)
> https://www.aitimes.kr/news/articleView.html?idxno=17314

**Comment by Heeseok-Jeong** [comment]
감사합니다 여러분! 이해됐어요~.~
