### ISSUE TITLE
[후미] 부동 소수점 처리

### ISSUE THREAD

**Issue by opijae** [boostcamp-ai-tech-4/peer-session#22]
### **🙌 질문자**

-  `후미`@opijae

----

### **❓ 질문 내용**

-  그림과 같이 두 벡터 내적을 이용해 각도를 구하러 합니다. (코사인 제2법칙 이용)
 
![image](https://user-images.githubusercontent.com/26226101/105793341-475a4f00-5fcc-11eb-9207-70e4e1d60f61.png)

```python
x=(1,1)
y=(2,2)
v=np.inner(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
print(v) # -> 0.9999999999999999
theta=np.arccos(v)
print(theta) # -> 2.1073424255447017e-08
print(theta==0) # -> False
```

구하려 했는데 부동소수점 때문에 0.0으로 딱 안나오네요 이럴땐 어떻게 처리해야될까요?
x=(1,1) y=(3,3)일 때는 내적은 1.0, 각도는 0.0라디안 True로 잘나옵니다.

----

**Comment by CoodingPenguin** [comment]
부동소수점을 소수점을 근사한거여서 웬만하면 `==`연산으로 비교하는 걸 권장하지 않더라고요. 

지금 든 생각으로는 직접 허용 에러 범위를 정해서 검사하는 방법 밖에 없을 것 같습니다ㅠㅠ

```python
error = 0.0000001
if abs(theta-0) < error:
    return True
else
    return False
```
