### ISSUE TITLE
[엠제이] 벡터의 미분

### ISSUE THREAD

**Issue by mj950425** [boostcamp-ai-tech-4/peer-session#25]
### **🙌 엠제이**

-  `엠제이` @mj950425 

----

### **❓ 질문 내용**

- 해당 이미지에서 별표 위에줄에 Xik가 맞는지 Xki가 맞는지 헷갈립니다.. 벡터를 미분하면 transpose된다고 했는데 저 부분은 어떻게 생각해야할지 모르겠네요
![image](https://user-images.githubusercontent.com/52944973/105833296-55c85b00-600c-11eb-9d5f-3f480dace440.png)

----

**Comment by Heeseok-Jeong** [comment]
x^T_ki 가 말이 되는진 모르겠는데, 전치한 상태에서 ki 원소니까 이렇게 되지 않을까 싶네요 ㄷㄷ

**Comment by Heeseok-Jeong** [comment]
저는 이거 루트 씌어져있어서 계산하기 쉽지않네요 ㅠ
<img width="380" alt="스크린샷 2021-01-26 오후 11 57 18" src="https://user-images.githubusercontent.com/37643891/105861625-44924500-6032-11eb-9144-32cfb70cc441.png">

**Comment by CoodingPenguin** [comment]
유도해보니까 수식을 행렬/벡터곱을 표현할 때 X_k가 **행렬곱 조건(AB일 때 A의 열의 크기 == B의 행의 크기)** 때문에 어쩔 수 없이 전치를 시켜야 되더라고요.

아래는 제가 유도한 건데 혹시 잘 안 보이시거나 이해가 안되는 부분이 있다면 Comment 달아주세요!!

----

![image](https://user-images.githubusercontent.com/37505775/105879352-6812bb00-6045-11eb-8c41-fd986e0bb08a.png)
![KakaoTalk_20210127_021359606](https://user-images.githubusercontent.com/37505775/105879448-8973a700-6045-11eb-8660-dee102b7595f.jpg)

**Comment by mj950425** [comment]
와,,, 펭귄님 존경합니다.
