### ISSUE TITLE
[펭귄] 몬테카를로 방법을 활용하여 원주율에 대한 근사값 구하기

### ISSUE THREAD

**Issue by CoodingPenguin** [boostcamp-ai-tech-4/peer-session#38]
### **🙌 질문자**

-  `펭귄` @CoodingPenguin

----

### **❓ 질문 내용**

- 몬테카를로 방법을 활용하여 원주율에 대한 근사값을 어떻게 구할 수 있을까요?

----

### **📄 참고 자료**
- [DAY 9] 확률론 맛보기 Further Question

----

**Comment by mj950425** [comment]
정사각형에 한변의 길이가 지름이 되도록 원을 넣고 샘플링해서 뽑히는 비율을 통해서 구해볼 수 있습니다.
피어세션을 활용해서 구현했던 코드입니다.
```python

import random
n=int(input())
cnt=0
for i in range(n):
    x= random.random() #0~1 사이 float을 뽑아준다!
    y= random.random()
    if x**2 + y**2 < 1:
        cnt+=1
print((cnt/n)*4)

```

**Comment by CoodingPenguin** [comment]
> 정사각형에 한변의 길이가 지름이 되도록 원을 넣고 샘플링해서 뽑히는 비율을 통해서 구해볼 수 있습니다.
> 피어세션을 활용해서 구현했던 코드입니다.
> 
> ```python
> import random
> n=int(input())
> cnt=0
> for i in range(n):
>     x= random.random() #0~1 사이 float을 뽑아준다!
>     y= random.random()
>     if x**2 + y**2 < 1:
>         cnt+=1
> print((cnt/n)*4)
> ```

`엠제이`님이 잘 설명해주셔서 추가 답변은 달지 않겠습니다! 
감사합니다!

혹시 **정사각형에 한변의 길이가 지름이 되도록 원을 넣고 샘플링해서 뽑히는 비율을 통해서 구해볼 수 있습니다** 부분이 직관적으로 이해가 안 되시면 아래 링크를 참고하시면 될 것 같습니다.

👉 [몬테카를로 알고리즘(Monte Carlo method)을 이용하여 확률적으로 원주율 구하기](https://m.blog.naver.com/PostView.nhn?blogId=rkdwnsdud555&logNo=220828040636&proxyReferer=https:%2F%2Fwww.google.com%2F)
