### ISSUE TITLE
[펭귄] 분류 문제에서 softmax 함수가 사용되는 이유가 뭘까요? 

### ISSUE THREAD

**Issue by CoodingPenguin** [boostcamp-ai-tech-4/peer-session#39]
### **🙌 질문자**

-  `펭귄` @CoodingPenguin

----

### **❓ 질문 내용**

- 분류 문제에서 softmax 함수가 사용되는 이유가 뭘까요? 
- softmax 함수의 결과값을 분류 모델의 학습에 어떤식으로 사용할 수 있을까요?

----

### **📄 참고 자료**
- [DAY 8] 딥러닝 학습방법 이해하기 Further Question

----

**Comment by jjerry-k** [comment]
분류 모델의 정답은 일반적으로 [0, 1, 0, 0] 과 같은 One-hot encoding 이죠! 
이 말은 1번 인덱스가 정답일 "확률" 을 의미합니다! 
그렇기에 분류의 출력을 확률로 해석할 수 있도록 해주는 softmax를 적용한 값과 정답값을 비교해서 학습을 합니다!

**Comment by CoodingPenguin** [comment]
@jjerry-k 답변 감사드립니다!

`제리`님 답변을 바탕으로 정리를 하자면

- 분류 모델에서 라벨은 one-hot encoding 형태로 `[0, 1, 0, 0]`으로 표현되는데
- 단순히 1번째 라벨값이다가 아닌 **이 데이터의 라벨은 1번째 라벨일 확률이 1이다**라고 해석할 수 있는 것이고 
- 이것과 비교를 하려면 예측값도 확률로 해석이 되어야하기 때문에 softmax를 써서 확률로 바꿔줘야 한다

는 말로 이해했는데 맞나요?

**Comment by jjerry-k** [comment]
@CoodingPenguin 

네! 맞습니다! 잘 이해하고 계시네요!

**Comment by CoodingPenguin** [comment]
@jjerry-k 감사합니다!
