### ISSUE TITLE
[히스] 표본분산에서의 N-1

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#40]
### **🙌 질문자**

-  히스@Heeseok-Jeong

----

### **❓ 질문 내용**

- 표본 분산에서 N 이 아니라 N-1 로 나누는 이유가 뭘까요?

----

**Comment by mj950425** [comment]
좋은 추정량이 되기 위해서는 불편성을 만족해야한다고 합니다. 이 말은 어떤 모수의 추정량의 기댓값이 실제 모집단의 모수와 같아야 한다는 말 같습니다. 그러기 위해서 수학적인 공식을 통해서 N대신 N-1이 대입되어야 수식적으로 같아짐을 아래 블로그에서 확인 할 수 있습니다!  

이러한 일이 발생하는 이유는, 나눠주는 N은 자유도로 구해야하는 변수를 뜻하는데, 정규분포에서 분산을 구하기 위해서  평균을 이미 구해놓았으므로, 하나 적은 N-1로 나눠준다고합니다. 좀 더 간단하게, 1을 빼줘야 모집단의 표준편차를 따라간다 라고 이해했습니다ㅎㅎ

https://m.blog.naver.com/ao9364/222023124818

**Comment by Heeseok-Jeong** [comment]
감사합니다 :)
