### ISSUE TITLE
[DAY 10] 시각화 / 통계학

### ISSUE THREAD

**Issue by keepRainy** [boostcamp-ai-tech-4/peer-session#41]
### ✋제안

[엠제이] / 자유롭게 슬랙에 카톡하듯이 질문했으면 좋겠습니다!

[서폿] / 모더레이터가 모두 적는 것 보다는 피어세션에서 질문자, 답변자가 구글독스에 짤막하게 정리하는 것이 더 효과적일것 같습니다!

[펭귄] / ```Futher Question``` 은 피어세션에서 다함께 얘기해보면 좋겠습니다!

---

### ❓질문

[펭귄] / 몬테카를로 방법을 활용하여 원주율에 대한 근사값을 어떻게 구할 수 있을까요?

* [엠제이]  
  정사각형안에 직접 점을 찍어보는 방식으로 근사시킬 수 있습니다  
  https://statkclee.github.io/r-algorithm/r-monte-carlo-pi.html

[히스] / 표본분산을 구할 때 N 이 아니라 N-1 로 나누는 이유가 무엇일까요?

* [펭귄]
   https://m.blog.naver.com/sw4r/221021838997  
  일반적으로 파라미터 예측치의 자유도는 파라미터를 예측하기 위해  
  중간과정에서 사용되는 파라미터의 수를 전체 독립적인 정보의 수에서 빼줘야 한다고 합니다  
  그러한 예로써, 샘플 분산은 N-1 자유도를 가지는데,  
  이유는 N개의 랜덤 정보에서 중간 과정에서 샘플 평균을 구해서 샘플 분산을 구해야 하기 때문에  
  그 파라미터 개수인 1개를 뺀 N-1 이 된다고 합니다

* [샐리]
  https://m.blog.naver.com/ao9364/222023124818

[펭귄] / 분류 문제에서 softmax 함수가 사용되는 이유가 뭘까요?

* [샐리]
  https://lv99.tistory.com/7

[샐리] / 엔트로피가 뭘까요?

* [서폿]
  http://melonicedlatte.com/machinelearning/2019/12/20/204900.html  
  http://melonicedlatte.com/machinelearning/2019/12/20/204900.html

* [샐리]
  (0.5, 0.5) = 엔트로피가 높다  
  (0.1, 0.9) = 엔트로피가 낮다

[서폿] / min-max scaling 이 뭘까요?

* [서폿]
  https://wotres.tistory.com/entry/min-max-scaling-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-in-python?category=930448

[원딜] / 소프트맥스를 확률로 해석하는 건가요? 의도적으로 그렇게 만든 것일까요?

* [All]
  그런것 같습니다...

[샐리] / ReLU

* [펭귄]
  기울기 소실 문제를 해결하는 것 같습니다  
  Leaky ReLU 도 같이 알아보면 좋을 것 같아요

[펭귄] softmax 함수의 결과값을 분류 모델의 학습에 어떤식으로 사용할 수 있을까요?

* [서폿]
  값을 키우는 거니 역전파가 더 잘되는 것 같습니다...?

[샐리] / 파란색 점들이 의미하는 바가 뭘까요?
![Screen Shot 2021-01-29 at 11 11 44 PM](https://user-images.githubusercontent.com/38286295/106285110-6b958480-6287-11eb-8531-8089edd51795.png)

* [엠제이]
  http://norman3.github.io/prml/docs/chapter01/5

---

### 🎉TMI 세미나

```엠제이``` 님에 대해서 많은 걸(?) 알게 된 유익한 시간이었습니다!!!

**Comment by changwoomon** [comment]
일주일동안 고생 많으셨습니당👍👍👍

**Comment by CoodingPenguin** [comment]
수고하셨습니다!!💪💪
