### ISSUE TITLE
[원딜] softmax 함수의 output이 실제로 확률인가요?

### ISSUE THREAD

**Issue by changwoomon** [boostcamp-ai-tech-4/peer-session#42]
### **🙌 질문자**

-  `원딜` @changwoomon

----

### **❓ 질문 내용**

- softmax 함수의 output이 실제로 확률인지 실제로 확률은 아니지만 확률의 성질들을 만족해서 확률처럼 해석이 되는 것인지가 궁금합니다!

----

### **📄 참고 자료**
- [DAY 8] 딥러닝 학습방법 이해하기 p.6
![image](https://user-images.githubusercontent.com/59998179/106293064-e9aa5900-6290-11eb-85d5-802df0a41e17.png)

----

**Comment by changwoomon** [comment]
실제 확률은 아니고, softmax 함수의 역할은 output을 **확률같이 해석할 수 있게** 해주는 것입니다.

output이 전부 0 이상의 값이고, 모든 값을 더하면 1이 되기 때문에 확률같이 해석할 수 있습니다.

[확률의 공리](https://j1w2k3.tistory.com/1307)

**Comment by Heeseok-Jeong** [comment]
생각도 못해봤는데 감사합니다!

**Comment by changwoomon** [comment]
@Heeseok-Jeong
단순 말장난 같기도 하고 더 생각하면 어려워질 것 같아 그냥 확률로 받아들이기로 했습니다... 하하
