### ISSUE TITLE
[히스] Valid 데이터와 Test 데이터

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#47]
### **🙌 질문자**

-  히스@Heeseok-Jeong

----

### **❓ 질문 내용**

- test 데이터를 valid 과정에서 사용하면 치팅이 된다고 하는데 왜그런걸까요? 파라미터를 안바꾸면 치팅이 아니지 않을까요?

----

**Comment by Heeseok-Jeong** [comment]
valid 에러와 train 에러의 비교를 통해 모델의 하이퍼파라미터를 수정하기 때문에, 즉 valid 데이터가 모델에 영향을 주기 때문에 test 데이터를 이 때 사용하면 치팅이 됩니다.

-피어세션-

**Comment by jjerry-k** [comment]
Train data: 모델 학습에 직접 영향
Validation data: 모델 학습에 간접 영향
Test data: 영향 없음
