### ISSUE TITLE
[히스] CNN 과 MLP 의 차이

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#48]
### **🙌 질문자**

-  히스@Heeseok-Jeong

----

### **❓ 질문 내용**

- CNN 과 MLP 가 어떤 차이를 갖는지 잘 모르겠습니다.

----

**Comment by Heeseok-Jeong** [comment]
우선 MLP 의 웨이트는 인풋과 아웃풋에 대한 연결을 위해 fully-connected 되는 반면, CNN 은 고정된 크기의 커널로 인풋을 이동하며 아웃풋을 만드는게 다릅니다.

CNN 을 사용하면 입력값에 대해 중첩적으로 벡터로 훑으면서 지나갈 수 있기 때문에 이미지 데이터 분류에서 더 피쳐를 잘 뽑아낼 수 있습니다. 또한 커널을 여러개 만들어 이미지의 피쳐를 분석하고 (커널마다 뽑아내는 피쳐가 다름, 하나는 명암, 하나는 테두리 이런식으로 뽑아냄) 이를 바탕으로 마지막에 flatten 을 통해 클래스 예측이 가능합니다.

**Comment by jjerry-k** [comment]
Convolution operation 의 유무!
