### ISSUE TITLE
[엠제이] adadelta를 통해서 천억개의 파라미터 연산량을 어떻게 줄여주는것일까?

### ISSUE THREAD

**Issue by opijae** [boostcamp-ai-tech-4/peer-session#49]
### **🙌 질문자**

- `엠제이` @mj950425  

----

### **❓ 질문 내용**

![image](https://user-images.githubusercontent.com/26226101/106566952-616bd280-6574-11eb-8dbd-d8e388f5c0e7.png)

- adadelta는  G를 구할 때 합을 구하는 대신 지수평균을 구해 메모리와 연산량을 줄인다고 알고 있습니다. 
어떻게 이 '지수 평균'을 통해 줄어드는지 궁금합니다.

----

**Comment by jjerry-k** [comment]
해당 부분 관련해선 도움이 될 만한 링크 올려드립니다!

RMSProp 부분부터 참고해보시면 좋을 것 같습니다!

[수식과 코드로 보는 경사하강법(SGD,Momentum,NAG,Adagrad,RMSprop,Adam,AdaDelta)](https://twinw.tistory.com/247)

**Comment by jjerry-k** [comment]
edwith 에 비슷한 질문이 들어왔네요! 
[https://www.edwith.org/bcaitech1/forum/48830](https://www.edwith.org/bcaitech1/forum/48830)
