### ISSUE TITLE
[서폿] solved.ac 플래티넘의 알고리즘 공부법

### ISSUE THREAD

**Issue by CoodingPenguin** [boostcamp-ai-tech-4/peer-session#5]
### **책**
- 종만북 절대 추천하지 않음
- TopCoder 빨간책 종만북보다 나으나 추천하지 않음

### **강의**

- [코드플러스 - 알고리즘 기초 강의](https://code.plus/bundle/7)
- [코드플러스 - 알고리즘 중급 1/3, 알고리즘 중급 2/3](https://code.plus/bundle/9) (중단)

### **문제 풀이**
- solved.ac 레벨별 풀기
  - 실버 3 이하, 하루에 3문제씩
  - 골드 4 이하, 하루에 3문제씩 + tistory 정리 (하루 1문제씩, 코드+풀이)
- 틀린 문제는 Notion으로 따로 관리
- 사람들이 많이 푼 문제일수록 검증된 문제이다!

> 이제 문제만 많이 풀고, 구글링해서 그때그때 공부한 것으로는 실력이 늘지 않는 것 같아
종만북을 공부하려고함.

**Comment by keepRainy** [comment]
너무 잘 정리해주셔서 추가적으로 덧붙일 팁은 없는 것 같아 이슈 닫겠습니다!

펭귄님, 감사합니다!
