### ISSUE TITLE
[히스] generative model 에서 generator 로 실제 아웃풋 생성

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#58]
### **🙌 질문자**

-  히스@Heeseok-Jeong

----

### **❓ 질문 내용**

- 분류, 회귀가 포함된 discriminator 는 입력 x 에 대한 출력을 예측한다면, generative model 에서 generator 는 입력에 대한 확률 분포를 만들어낸다고 알고 있습니다. 이 확률 분포를 이용해서 어떻게 실제 오브젝트 (남자 얼굴 등) 를 생성해내는지 궁금합니다..!

----

**Comment by jjerry-k** [comment]
음 latent vector 에 대해 먼저 말씀을 드려야할 것 같습니다! 

Generative model을 얘기할때는 latent vector를 빼고 얘기할 수가 없는데요!

이 **1차원 vector 안에 어떤 오브젝트를 생성할 지에 대한 정보가 적혀있다**고 생각하시면 됩니다!

**Comment by Heeseok-Jeong** [comment]
아하 감사합니다!!
