### ISSUE TITLE
[DAY 15] Generative model

### ISSUE THREAD

**Issue by opijae** [boostcamp-ai-tech-4/peer-session#60]
### 팀 데이터셋 작업 계획
- 2월 9일 화요일 14~17시 예정
- 조유리즈 (김채원, 조유리, 최예나) 구분하는 모델 만들기
- 한 레이블당 1200장 (train data set : 1000장  test data set 200장)
- 처음에는 이미지 자르기(crop)이나 전처리 없이 기본으로 해보자
   - 점진적으로 이미지 전처리 , 모델 & 코드 개선으로 성능 업 시키자
---
### 질문
- `후미` (트랜스포머) 멀티헤드에서 사용되는 Wo, 디코더에 들어가는 인풋
   -  https://github.com/boostcamp-ai-tech-4/peer-session/issues/59
- `히스` generative model 에서 generator 로 실제 아웃풋 생성 
   -  https://github.com/boostcamp-ai-tech-4/peer-session/issues/58
- `펭귄` 만 rgb에서 전부 independent 하면 나오는 변수의 개수
![image](https://user-images.githubusercontent.com/26226101/107053940-ccd2d000-6812-11eb-82a3-13d7b519e9be.png)
   - (R,G,B) 각각 들어갈 변수의 수가 3개니 '3'이 나온다.
- `히스`  이 식에 대해
![image](https://user-images.githubusercontent.com/26226101/107054145-17544c80-6813-11eb-96b9-a8a499131434.png)
   - 
![image](https://user-images.githubusercontent.com/26226101/107054273-3d79ec80-6813-11eb-8bab-5bc9065faa02.png)
   - 다음과 같이 0과 1로 이루어진 그림의 총 픽셀 수 n 일때 dependent일때와 independent일때의 경우의 수 
   - dependent : 서로 다른 픽셀의 값들을 고려함. 각 픽셀에 대한 경우의 수 2, 픽셀의 수 n => 2^n
   - independent : 서로 다른 픽셀의 값들을 고려하지않고 자신만 생각. 픽셀의 수 n => n
---
- 일주일 동안 고생 많으셨습니다.!!

**Comment by CoodingPenguin** [comment]
이번 주 모더레이터 정말 수고하셨습니다💪💪
