### ISSUE TITLE
[히스] GloVe 와 Word2Vec 의 차이가 무엇인가요?

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#61]
### **🙌 질문자**

-  히스@Heeseok-Jeong

----

### **❓ 질문 내용**

- 단어를 임베딩하는 두 가지 방법에서 GloVe 와 Word2Vec 의 차이가 무엇인가요?

----

**Comment by jjerry-k** [comment]
[참고 자료](https://ratsgo.github.io/from%20frequency%20to%20semantics/2017/03/11/embedding/)

**Comment by Heeseok-Jeong** [comment]
GloVe : 임베딩된 단어벡터 간 유사도 측정을 수월하게 하면서도 말뭉치 전체의 통계 정보를 좀 더 잘 반영해보자!
