### ISSUE TITLE
[MJ] 똑같은 단어가 있으면 Word2vec이 어떻게 동작하는지?

### ISSUE THREAD

**Issue by mj950425** [boostcamp-ai-tech-4/peer-session#63]
### 🙌 질문자

-   `MJ` @mj950425
----

### **❓ 질문 내용**

- skip gram에서 똑같은 단어가 문장내에 있으면 어떻게 동작할까

----

**Comment by CoodingPenguin** [comment]
http://jalammar.github.io/illustrated-word2vec/

위의 자료의 `Skipgram` 부분을 참고했을 때 똑같은 단어가 문장에 있는 것과 상관없이 윈도우를 슬라이딩 하면서 `(input, output)` 쌍을 만드는 것 같습니다!
그래서 GloVe에서 교수님이 말씀해주셨던 것처럼 **Word2Vec에는 똑같은 `(input, output)` 쌍이 있을 수 있다**는 그 말이 중복 여부와 상관없이 슬라이딩 하면서 쌍을 만들어서 그런 말이 나온 것 같습니다.
