### ISSUE TITLE
[히스] Word2Vector 의 목적

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#65]
### **🙌 질문자**

-  히스@HeeseokJeong

----

### **❓ 질문 내용**

- Word2Vector 의 목적이 단어간 유사도를 구해주는 것이라 알고 있습니다. 즉, 현재 문장 내 단어들 간 유사도를 잘 잡아내는 모델을 만드는 것인데, 수업에서는 Embedding 시켜주는 웨이트들만 나중에 사용한다 하셨습니다. 그러면 만들어진 모델은 직접적으로 사용하지 않고, 다른 곳에서 단어 임베딩이 필요할 때 저 웨이트들만 사용하려고 학습시키는건가요?

----

**Comment by jjerry-k** [comment]
음......Word2vec이 "단어간 유사도를 구한다" 도 맞고 "Embedding 방법이다" 도 맞습니다.
다시 말하면 "유사한 단어 빈도를 기반으로 Word를 Vector로 Embedding 한다" 라고 할 수 있지 않을까요? 

그리고 말씀하신것처럼 다른 모델의 입력으로 들어가기 전에 word embedding시에 사용할 수 있겠죠!

**Comment by Heeseok-Jeong** [comment]
둘 다 가능하고 목적에 맞게 사용하면 된다! 감사합니다!!
