### ISSUE TITLE
[히스] LSTM과 GRU 는 백프로파게이션을 셀 스테이트에 대해서만 하나요?

### ISSUE THREAD

**Issue by Heeseok-Jeong** [boostcamp-ai-tech-4/peer-session#66]
### **🙌 질문자**

- 히스@HeeseokJeong

----

### **❓ 질문 내용**

- 
<img width="1209" alt="스크린샷 2021-02-16 오후 6 35 29" src="https://user-images.githubusercontent.com/37643891/108044557-c0a60880-7085-11eb-9550-e05cdcc183a7.png">
 LSTM과 GRU 는 백프로파게이션을 셀 스테이트에 대해서만 하나요?

----

**Comment by jjerry-k** [comment]
Weight가 있는 모든 부분에서 backpropgation 이 이루어집니다!

**Comment by Heeseok-Jeong** [comment]
감사합니디ㅏ!
