### ISSUE TITLE
[원딜] (FQ) Attention

### ISSUE THREAD

**Issue by changwoomon** [boostcamp-ai-tech-4/peer-session#76]
### **❓ 질문 내용**

- Attention은 이름 그대로 어떤 단어의 정보를 얼마나 가져올 지 알려주는 직관적인 방법처럼 보입니다. Attention을 모델의 Output을 설명하는 데에 활용할 수 있을까요?

----

### **📄 참고 자료**
- DAY 19. Transformer
- [Attention is not Explanation](https://arxiv.org/pdf/1902.10186.pdf)
- [Attention is not not Explanation](https://www.aclweb.org/anthology/D19-1002.pdf)

----

**Comment by jjerry-k** [comment]
음.. `Attention을 모델의 Output을 설명하는 데에 활용할 수 있을까요?` 에 대해 다시 설명 부탁드려도 될까요?

**Comment by changwoomon** [comment]
> 음.. `Attention을 모델의 Output을 설명하는 데에 활용할 수 있을까요?` 에 대해 다시 설명 부탁드려도 될까요?

앗 답장이 늦었네요,,,
수업에 달려있는 Further Question을 그대로 가져온 거라 정확히는 모르겠지만, Attention을 수행해서 나오는 행렬들을 통해 단어들 간의 관계를 유추할 수 있는지를 물어보는 것이라고 생각하고 피어세션 때 진행했습니다!
