### ISSUE TITLE
[DAY 22] 페이지랭크 & 전파 모델

### ISSUE THREAD

**Issue by mj950425** [boostcamp-ai-tech-4/peer-session#85]
---
### 😜**잡담**
- MJ @mj950425 
모더레이터 진행력 부족

- 원딜 @changwoomon 
밤새서 공부

-  히스 @Heeseok-Jeong
SW 카톡방 추천

-  서폿 @opijae 
캠이 까맣게 나오는데 이유는 잘 모르겠음.

-  셀리 @bsm8734 
선배 만나러 카페옴

-  펭귄 @CoodingPenguin 
스타트업 인턴 경험
---
---

#### 🤷‍♀️Further Question🤷‍♀️
- 감염병의 전파를 모델링 하기 위해서는 감염과 더불어 감염된 환자의 회복을 고려해야 합니다. 감염된 사람이 회복될 수 있고, 한 번 감염이 된 사람은 추가적으로 감염이 되지 않는다고 가정한다면 어떻게 전파 모델을 설계할 수 있을까요? 

- 엣지를 지운다. or 노드를 지운다.

- 따로 테이블을 만들어서 관리한다.

- SIR 모델을 적용한다.
#### 참조링크
SIS, SIR 모델을 COVID에 적용한 사례
http://www.thothsaem.com/wp-content/uploads/2020/02/SIS_model-1.pdf
http://www.thothsaem.com/wp-content/uploads/2020/03/SIR_model_0320.pdf
https://benbennben.github.io/covid-19/
http://www.thothsaem.com/wp-content/uploads/2020/03/SIR_model_0320.pdf

---

**Comment by changwoomon** [comment]
Ans. 감염 후보자(S), 감염자(I), 회복자(R)을 모두 고려한 SIR 모델이 있습니다. 아래의 링크를 참고하세요!
https://www.maa.org/press/periodicals/loci/joma/the-sir-model-for-spread-of-disease-the-differential-equation-model
